### ISSUE TITLE
"Usage" section from README seems either wrong or incomplete

### ISSUE THREAD

**Issue by matheushent** [omnivector-solutions/slurmd-operator#19]
### Bug Description

Trying to deploy the slurm operators today by following the steps defined in the #usage section from the README and it seems wrong (some relations don't work and there are some misspellings as well).

What worked for me:

```bash
juju deploy slurmctld --channel edge
juju deploy slurmd compute --channel edge -n 2
juju deploy slurmdbd --channel edge
juju deploy mysql --channel 8.0/stable
juju deploy slurmrestd --chanel edge

juju integrate slurmctld:slurmd compute:slurmd
juju integrate slurmctld:slurmdbd slurmdbd:slurmdbd
juju integrate slurmctld:slurmrestd slurmrestd:slurmrestd
juju integrate mysql:database slurmdbd:database
```

### To Reproduce

1. juju deploy slurmctld --channel edge
2. juju deploy slurmd --channel edge
3. juju deploy slurmdbd --channel edge
4. juju deploy mysql --channel 8.0/stable
5. juju deploy mysql-router slurmdbd-mysql-router --channel 8.0/stable
6. juju integrate slurmctld:slurmd slurmd:slurmd
7. juju integrate slurmdbd-mysql-router:backend-database mysql:database
8. juju integrate slurmdbd:database slurm-mysql-router:database
9. juju integrate slurmctld:slurmdbd slurmdbd:slurmdbd

### Environment

I'm running juju 3.2/stable inside a Multipass VM whose OS is jammy. Instructions to get the set up going:

1. `multipass launch -c8 -m6G -d40G -nvantage jammy`
2. `multipass shell vantage`
3. 
```bash
sudo snap install juju --classic --channel 3.2/stable
sudo snap install --stable charmcraft --classic
mkdir -p ~/.local/share
```
4.
```bash
lxd init --auto
lxc network set lxdbr0 ipv6.address none
```
5. `sudo apt install make`
6. `juju bootstrap localhost/localhost vantage`
7. `juju add-model rats`

The CPU architecture is amd64. Both Multipass and multipassd are running version `1.12.2`.

### Relevant log output

```shell
No relevant log output
```

**Comment by jaimesouza** [comment]
@NucciTheBoss, for me it is failing at:
```
$ juju integrate slurmdbd-mysql-router:backend-database mysql:database

ERROR application "slurmdbd-mysql-router" has no "backend-database" relation
```

Do you know if something changed in the charm recently?

And 

`juju integrate slurmdbd:database slurm-mysql-router:database`

Should be 

`juju integrate slurmdbd:database slurmdbd-mysql-router:database`

**Comment by NucciTheBoss** [comment]
@jaimesouza can you test mysql-router with `--channel edge`? That might be the issue.

@matheushent were there any other issues you encountered? Looks like the only issue was with the MySQL router.

**Comment by jaimesouza** [comment]
@NucciTheBoss I tried with` juju deploy mysql-router slurmdbd-mysql-router --channel dpe/edge` and it worked.

**Comment by jaimesouza** [comment]
@NucciTheBoss, in summary we need this:

```
juju deploy slurmctld --channel edge
juju deploy slurmd --channel edge
juju deploy slurmdbd --channel edge
juju deploy mysql --channel 8.0/edge
juju deploy mysql-router slurmdbd-mysql-router --channel dpe/edge
juju integrate slurmctld:slurmd slurmd:slurmd
juju integrate slurmdbd-mysql-router:backend-database mysql:database
juju integrate slurmdbd:database slurmdbd-mysql-router:database
juju integrate slurmctld:slurmdbd slurmdbd:slurmdbd
```

**Comment by jaimesouza** [comment]
I will create the PRs to update the README.md

**Comment by jaimesouza** [comment]
@NucciTheBoss the slurmctld service is not starting.

The reason:

`[2023-07-27T20:53:46.452] fatal: You are running with a database but for some reason we have no TRES from it.  This should only happen if the database is down and you don't have any state files.`

It looks like it can not connect to the database.

**Comment by NucciTheBoss** [comment]
@jaimesouza Okay, let me triage the issue with the database, however, the README can be fixed by changing the instructions to:

```shell
juju deploy slurmctld --channel edge
juju deploy slurmd --channel edge
juju deploy slurmdbd --channel edge
juju deploy mysql --channel 8.0/edge
juju deploy mysql-router slurmdbd-mysql-router --channel dpe/edge
juju integrate slurmctld:slurmd slurmd:slurmd
juju integrate slurmdbd-mysql-router:backend-database mysql:database
juju integrate slurmdbd:database slurmdbd-mysql-router:database
juju integrate slurmctld:slurmdbd slurmdbd:slurmdbd
```

The new MySQL charm (ops-based) was moved to the 8.0/edge branch, but the new MySQL router charm is still on dpe/edge. This should close out Matheus's initial issue (the documentation being incorrect), but I will check what is going on with the database.

**Comment by matheushent** [comment]
I can confirm the initial issue was solved by adding the `--channel edge` flag, so I'm closing the issue.
